### ISSUE TITLE
Thinking About adding this library

### ISSUE THREAD

**Issue by john-cinquegrana** [Nodding/DistantWaters#1]
# Vue Library

https://element-plus.org/en-US/

The best thing about having something like Vue/React/Angularjs is that you don't need to make your own components, I'm just going to steal them from here.

**Comment by john-cinquegrana** [comment]
Actually I'm nearly 100% into adding this component library https://vuetifyjs.com/, and probably getting rid of tailwind since it's so outside the current ecosystem. This thing seems really nice, lots of built ins and very customizable.

**Comment by Nodding** [comment]
Go for it. Im in favor of trimming whatever we don't need for stuff to make our lives easier.
